set positional-arguments

# Display help
help:
    just -l

# `nori`
alias n := nori
nori *args:
    cargo run --bin nori -- "$@"

# format code
fmt:
    cargo fmt -- --config imports_granularity=Item

fix *args:
    cargo clippy --fix --all-features --tests --allow-dirty "$@"

clippy:
    cargo clippy --all-features --tests "$@"

install:
    rustup show active-toolchain
    cargo fetch

# Prefer running targeted tests on single packages,
# for faster work within the monorepo
test *args:
    cargo test "$@"

# Run `cargo nextest` since it's faster than `cargo test`, though including
# --no-fail-fast is important to ensure all tests are run.
#
# Run `cargo install cargo-nextest` if you don't have it installed.
nextest:
    cargo nextest run --no-fail-fast
